import { chromium } from 'playwright';
const sleep = ms => new Promise(r=>setTimeout(r,ms));
const browser = await chromium.launch({ channel: 'chromium' });
const ctx = await browser.newContext({ viewport:{width:1366,height:900} });
const page = await ctx.newPage();
const log=[];
page.on('console', m=>{ if(m.type()==='error') log.push('console: '+m.text().slice(0,200)); });
page.on('response', async r=>{ const u=r.url(); if(u.includes('admin-ajax')||u.includes('wp-json')||r.request().method()==='POST'){ let b=''; try{b=(await r.text()).slice(0,300);}catch(e){} log.push(r.request().method()+' '+r.status()+' '+u.slice(0,120)+' :: '+(r.request().postData()||'').slice(0,200)+' => '+b); }});
await page.goto('https://blog.123greetings.com/archive/', {waitUntil:'networkidle', timeout:60000});
const count = async()=> await page.evaluate(()=>new Set([...document.querySelectorAll('.penci-wrapper-posts-content a[href], article a[href], .penci-grid a[href]')].map(a=>a.href).filter(h=>/blog\.123greetings\.com\/[^/]+\/$/.test(h))).size);
console.log('before', await count());
await page.locator('.penci-ajax-more-button').scrollIntoViewIfNeeded();
await sleep(1000);
await page.locator('.penci-ajax-more-button').click();
await sleep(6000);
console.log('after1', await count(), await page.locator('.penci-ajax-more-button').innerText().catch(()=>'-'));
await page.locator('.penci-ajax-more-button').click().catch(e=>console.log('click2 err',e.message.slice(0,100)));
await sleep(6000);
console.log('after2', await count(), await page.locator('.penci-ajax-more-button').innerText().catch(()=>'-'));
console.log(log.join('\n'));
await page.screenshot({path:'agent-work/seo-verify/shots/archive_after.png', fullPage:false});
await browser.close();
